### ISSUE TITLE
[Question] What do I do after downloading my email template?

### ISSUE THREAD

**Issue by mohshbool** [mysigmail/html-email-templates#1]
First of all, great job. Incredibly well-made.

My question is, how I do import the html/css files into an email client such as Spark? Just basically how do I send an email with the template I created on MySigMail Card?

Again, thanks for making this open-source. Been searching for something like this for a while.

Totally unrelated: I do internationalization if you're interested in making your platform reach a bigger wider range of people 😄.

**Comment by antonreshetov** [comment]
Hi @mohshbool,

Thank you for your feedback. To send an HTML email you need to use an ESP (email service provider) such as MailChimp, Mailgun etc.

Thank you for the offer, I will keep in mind!

**Comment by mohshbool** [comment]
> Hi @mohshbool,
> 
> Thank you for your feedback. To send an HTML email you need to use an ESP (email service provider) such as MailChimp, Mailgun etc.
> 
> Thank you for the offer, I will keep in mind!

Thank you for the incredibly fast response.

I will check out my options, I think I have a MailChimp account.

As for internationalization. I'm fully able to do the Arabic translation, as I'm currently a member of Facebook's (Mainly React) internationalization team and the VueJS team.

Feel free to reach out whenever you feel like it.
