### ISSUE TITLE
'No Need to create an account or login'

### ISSUE THREAD

**Issue by pyrosyndicate** [mysigmail/html-email-templates#5]
![image](https://user-images.githubusercontent.com/33336125/226892921-b17d5b4a-3255-40b8-a6aa-deb93576b145.png)

**Comment by pyrosyndicate** [comment]
Could you please explain as to why it is requesting I login?

**Comment by antonreshetov** [comment]
@pyrosyndicate A follow-up question, why did you open an issue in the static html email templates repository?

**Comment by pyrosyndicate** [comment]
This is the repo I landed on and the info states that there is no login required so I gave it a quick try and the first thing when I tried to drag and drop was a login screen, is there a better place to ask the question?

**Comment by antonreshetov** [comment]
Login is required to use the SaaS MySigMail Card. The Card is now closed for account creation and login. Card is now moving to [open source](https://github.com/mysigmail/card).

**Comment by pyrosyndicate** [comment]
Amazing, thank you for the explanation. the program looks amazing, great work. I wish you/your team all the best in the future.
